project_name        = "devsecops"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
availability_zone   = "ap-south-1a"
enable_nat          = true
ecs_container_image = "090965606124.dkr.ecr.ap-south-1.amazonaws.com/aspire-devsecops:latest"
mongodb_connection_uri = "mongodb://username:password@host:port/database?option1=value1&option2=value2"
aws_region             = "ap-south-1"